If a log is sent as discord attachment, it will upload it to the SMAPI site.
aquova/governor pull request #24
Opened 2022-07-14 10:12 UTC by AnotherPillow

If someone sends a log as a discord attachment, the bot will send the URL on the smapi site to the channel.
I don't know what happened with commit/changes if I'm going to be honest, I used VSC for it so blame microsoft™.

2022-07-14 12:59 UTC, aquova requested changes
I have some formatting issues, but overall I think this looks good and should work well.

2022-07-14 12:59 UTC, aquova commented on src/main.py
> -# Governor
It looks like the file was converted from Unix line endings to Windows ones. In VSCode down in the lower right, there's the option of "CRLF" or "LF". If you have it as "LF" when you save, it won't overwrite every line like this. I would like to keep the git history, so I would request that we do this, otherwise this commit is very unclear.

2022-07-14 12:59 UTC, aquova commented on src/main.py
> +            if attachment.filename == "SMAPI-latest.txt":
According to https://smapi.io/log "SMAPI-crash.txt" is also a valid log filename

2022-07-14 12:59 UTC, aquova commented on src/main.py
> +                print("SMAPI-latest.txt found")
idk if we need to print this out to the console, it just clutters things up, remove.

2022-07-14 12:59 UTC, aquova commented on src/main.py
> +                #await message.channel.send(a.url)
Remove unused line

2022-07-14 12:59 UTC, aquova commented on src/main.py
> +    for attachment in message.attachments:
Four spaces per indent

2022-07-14 16:00 UTC, AnotherPillow commented
The console thing was from testing, I'll fix the indents and I changed the end of line sequence to LF, but won't that change the git history again?

2022-07-15 08:05 UTC, AnotherPillow commented
Whoops didn't mean to press the request a review button, sorry

2022-07-15 16:23 UTC, aquova commented
> The console thing was from testing, I'll fix the indents and I changed the end of line sequence to LF, but won't that change the git history again?

When I go to accept the pull request, I can squash all the changes into a single commit, which should then only show the actual changes made.

2022-07-15 16:24 UTC, aquova commented
Everything looks good. I'll do some testing to make sure once I have some free time later today, but nothing sticks out to me for now.

2022-07-16 02:31 UTC, merged

2022-07-16 02:32 UTC, aquova commented
This is pretty slick. The one thing to note is that if an invalid SMAPI log is processed, the bot will throw an index error when attempting to parse the URL. I think the odds of this are pretty low, if someone is uploading a file with that exact filename, it's probably valid, but it's something I'll keep an eye on in the future.